default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000
  username: mak4alex
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: power_development

test:
  <<: *default
  database: power_test

production:
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV['DATABASE_POOL'] || 5 %>
  host: <%= ENV['DATABASE_SERVER_URL'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  username: <%= ENV['DATABASE_USER_NAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
